name: Scheduled Deploy

on:
  schedule:
    # Runs every day at 2 AM UTC
    - cron:  '45 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Cloudflare Pages
      run: sh ./auto_commit.sh