name: Scheduled Deploy

on:
  schedule:
    # Runs 2 times every day
    - cron: '* */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Add History
        run: echo auto_commit_`date "+%Y%m%d"` >>history
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto Commit